=== JoachimR/CzechLosungenParser/xslt/losungen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="FreeXml" type="Losungen">
	</xs:element>
	<xs:complexType name="Losungen">
		<xs:sequence>
			<xs:element name="Losungen" type="Losung" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Losungen">
		<xs:sequence>
			<xs:element name="Datum" type="xs:string"/>
			<xs:element name="Wtag" type="xs:string"/>
			<xs:element name="Sonntag" type="xs:string"/>
			<xs:element name="Losungstext" type="xs:string"/>
			<xs:element name="Losungsvers" type="xs:string"/>
			<xs:element name="Lehrtext" type="xs:string"/>
			<xs:element name="Lehrtextvers" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== JoachimR/CzechLosungenParser/xslt/result2016.xml
<?xml version="1.0" encoding="UTF-8"?>
<FreeXml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="http://losungen.de/losungen.xsd">

    <Losungen>
        <Datum>2016-01-01</Datum>
        <Sonntag>Nový Rok</Sonntag>
        <Wtag>Pátek</Wtag>
        <Losungstext>Chválu vzdejte Pánu pánů, jeho milosrdenství je věčné. Jedině on koná velké divy, jeho
            milosrdenství je věčné.
        </Losungstext>
        <Losungsvers>Žalm 136,3.4</Losungsvers>
        <Lehrtext>Tomu pak, který působením své moci mezi námi může učinit nade všechno víc, než zač prosíme a co si
            dovedeme představit, jemu samému buď sláva v církvi a v Kristu Ježíši po všecka pokolení na věky věků! Amen.
        </Lehrtext>
        <Lehrtextvers>Efezským 3,20-21</Lehrtextvers>
    </Losungen>
    <Losungen>
        <Datum>2016-01-02</Datum>
        <Sonntag/>
        <Wtag>Sobota</Wtag>
        <Losungstext>Vodí mne po stezkách spravedlnosti pro jméno své.</Losungstext>
        <Losungsvers>Žalm 23,3 K</Losungsvers>
        <Lehrtext>Moje ovce slyší můj hlas, já je znám, jdou za mnou.</Lehrtext>
        <Lehrtextvers>Jan 10,27</Lehrtextvers>
    </Losungen>
    <Losungen>
        <Datum>2016-01-03</Datum>
        <Sonntag>2. Neděle po vánocích</Sonntag>
        <Wtag>Neděle</Wtag>
        <Losungstext>Pojďte, klaňme se, padněme tváří k zemi před Bohem, jenž nás stvořil.</Losungstext>
        <Losungsvers>Žalm 95,6 F</Losungsvers>
        <Lehrtext>On vás povolal ze tmy v předivné světlo své.</Lehrtext>
        <Lehrtextvers>1.Petrova 2,9 K</Lehrtextvers>
    </Losungen>
    <Losungen>
        <Datum>2016-01-04</Datum>
        <Sonntag/>
        <Wtag>Pondělí</Wtag>
        <Losungstext>Vyzpytuj mne, Bože silný, a poznej srdce mé; zkus mne, a poznej myšlení má. A popatř, chodím-liť já
            cestou odpornou tobě, a veď mne cestou věčnou.
        </Losungstext>
        <Losungsvers>Žalm 139,23-24 K</Losungsvers>
        <Lehrtext>Ať Kristus vírou přebývá ve vašich srdcích.</Lehrtext>
        <Lehrtextvers>Efezským 3,17 Ž</Lehrtextvers>
    </Losungen>
    <Losungen>
        <Datum>2016-01-05</Datum>
        <Sonntag/>
        <Wtag>Úterý</Wtag>
        <Losungstext>Nasyť nás svým milosrdenstvím hned ráno a po všechny dny se budeme radovat a plesat.</Losungstext>
        <Losungsvers>Žalm 90,14</Losungsvers>
        <Lehrtext>Všecken lid na úsvitě přicházel k němu do chrámu, aby ho poslouchal.</Lehrtext>
        <Lehrtextvers>Lukáš 21,38 K</Lehrtextvers>
    </Losungen>
    <Losungen>
        <Datum>2016-01-06</Datum>
        <Sonntag>Zjevení Páně - Epifanias</Sonntag>
        <Wtag>Středa</Wtag>
        <Losungstext>Tvá jsou nebesa, tvá je i země, založil jsi svět a všechno, co je na něm. Ty jsi stvořil jih i
            sever.
        </Losungstext>
        <Losungsvers>Žalm 89,12-13</Losungsvers>
        <Lehrtext>V Kristu bylo stvořeno všechno na nebi i na zemi - svět viditelný i neviditelný; jak nebeské trůny,
            tak i panstva, vlády a mocnosti - a všechno je stvořeno skrze něho a pro něho.
        </Lehrtext>
        <Lehrtextvers>Koloským 1,16</Lehrtextvers>
    </Losungen>
    <Losungen>
        <Datum>2016-01-07</Datum>
        <Sonntag/>
        <Wtag>Čtvrtek</Wtag>
        <Losungstext>Všechny národy, které jsi stvořil, přicházeti a klaněti se budou před tebou, i uctívati budou jméno
            tvé.
        </Losungstext>
        <Losungsvers>Žalm 86,9 F</Losungsvers>
        <Lehrtext>Ukázala se Boží milost, která přináší spásu všem lidem.</Lehrtext>
        <Lehrtextvers>Titovi 2,11</Lehrtextvers>
    </Losungen>
    <Losungen>
        <Datum>2016-01-08</Datum>
        <Sonntag/>
        <Wtag>Pátek</Wtag>
        <Losungstext>Zorejte svůj úhor, dokud je čas dotázat se Hospodina. Až přijde, svlaží vás spravedlností.
        </Losungstext>
        <Losungsvers>Ozeáš 10,12</Losungsvers>
        <Lehrtext>Nepřizpůsobujte se tomuto věku, nýbrž proměňujte se obnovou své mysli, abyste mohli rozpoznat, co je
            vůle Boží, co je dobré, Bohu milé a dokonalé.
        </Lehrtext>
        <Lehrtextvers>Římanům 12,2</Lehrtextvers>
    </Losungen>
    <Losungen>
        <Datum>2016-01-09</Datum>
        <Sonntag/>
        <Wtag>Sobota</Wtag>
        <Losungstext>Hospodin jest útočiště chudého, útočiště v čas soužení.</Losungstext>
        <Losungsvers>Žalm 9,10 K</Losungsvers>
        <Lehrtext>Rád přijímám slabost, urážky, útrapy, pronásledování a úzkosti pro Krista.</Lehrtext>
        <Lehrtextvers>2.Korintským 12,10</Lehrtextvers>
    </Losungen>
    <Losungen>
        <Datum>2016-01-10</Datum>
        <Sonntag>1. neděle po Zjevení Páně</Sonntag>
        <Wtag>Neděle</Wtag>
        <Losungstext>Dám jim jedno srdce a vložím do jejich nitra nového ducha, odstraním z jejich těla srdce kamenné a
            dám jim srdce z masa, aby se řídili mými nařízeními, zachovávali moje řády a jednali podle nich.
        </Losungstext>
        <Losungsvers>Ezechiel 11,19.20</Losungsvers>
        <Lehrtext>Kdo je v Kristu, je nové stvoření. Co je staré, pominulo, hle, je tu nové!</Lehrtext>
        <Lehrtextvers>2.Korintským 5,17</Lehrtextvers>
    </Losungen>
    <Losungen>
        <Datum>2016-01-11</Datum>
        <Sonntag/>
        <Wtag>Pondělí</Wtag>
        <Losungstext>Těš se v Hospodinu, a dá tobě žádosti srdce tvého.</Losungstext>
        <Losungsvers>Žalm 37,4 K</Losungsvers>
        <Lehrtext>Všecko, oč v modlitbě prosíte, je vám dáno, a budete to mít.</Lehrtext>
        <Lehrtextvers>Marek 11,24</Lehrtextvers>
    </Losungen>
    <Losungen>
        <Datum>2016-01-12</Datum>
        <Sonntag/>
        <Wtag>Úterý</Wtag>
        <Losungstext>Kdo člověku vládne spravedlivě, ten, kdo vládne v Boží bázni, je jak jitřní světlo při východu
            slunce.
        </Losungstext>
        <Losungsvers>2.Samuelova 23,3-4</Losungsvers>
        <Lehrtext>Dávejte pozor na sebe i na celé stádo, ve kterém si vás Duch svatý ustanovil za strážce, abyste byli
            pastýři.
        </Lehrtext>
        <Lehrtextvers>Skutky 20,28</Lehrtextvers>
    </Losungen>
    <Losungen>
        <Datum>2016-01-13</Datum>
        <Sonntag/>
        <Wtag>Středa</Wtag>
        <Losungstext>Já s ním budu v tísni, vysvobodím ho a oslavím ho.</Losungstext>
        <Losungsvers>Žalm 91,15 Z</Losungsvers>
        <Lehrtext>Ježíš vysvobodil ty, kdo byli strachem před smrtí drženi po celý život v otroctví.</Lehrtext>
        <Lehrtextvers>Židům 2,15</Lehrtextvers>
    </Losungen>
    <Losungen>
        <Datum>2016-01-14</Datum>
        <Sonntag/>
        <Wtag>Čtvrtek</Wtag>
        <Losungstext>Žádný obyvatel už neřekne "Jsem nemocný"; lidu, jenž tam sídlí, bude odpuštěno provinění.
        </Losungstext>
        <Losungsvers>Izaiáš 33,24 J</Losungsvers>
        <Lehrtext>Ježíš řekl ochrnutému: "Synu, odpouštějí se ti hříchy."</Lehrtext>
        <Lehrtextvers>Marek 2,5</Lehrtextvers>
    </Losungen>
    <Losungen>
        <Datum>2016-01-15</Datum>
        <Sonntag/>
        <Wtag>Pátek</Wtag>
        <Losungstext>Ty mě, Hospodine, znáš a vidíš mě, zkoušíš mé srdce, je-li s tebou.</Losungstext>
        <Losungsvers>Jeremiáš 12,3</Losungsvers>
        <Lehrtext>Nevyslovujte soudy předčasně, dokud Pán nepřijde. On vynese na světlo to, co je skryto ve tmě, a zjeví
            záměry srdcí; tehdy se člověku dostane chvály od Boha.
        </Lehrtext>
        <Lehrtextvers>1.Korintským 4,5</Lehrtextvers>
    </Losungen>
    <Losungen>
        <Datum>2016-01-16</Datum>
        <Sonntag/>
        <Wtag>Sobota</Wtag>
        <Losungstext>Nebudeš míti bohů jiných přede mnou.</Losungstext>
        <Losungsvers>2.Mojžíšova 20,3 K</Losungsvers>
        <Lehrtext>Nikdo nemůže sloužit dvěma pánům.</Lehrtext>
        <Lehrtextvers>Matouš 6,24</Lehrtextvers>
    </Losungen>
    <Losungen>
        <Datum>2016-01-17</Datum>
        <Sonntag>Poslední neděle po Zjevení Páně</Sonntag>
        <Wtag>Neděle</Wtag>
        <Losungstext>Lid můj dobroty mé nasytí se, dí Hospodin.</Losungstext>
        <Losungsvers>Jeremiáš 31,14 K</Losungsvers>
        <Lehrtext>Bůh má moc zahrnout vás všemi dary své milosti, abyste vždycky měli dostatek všeho, co potřebujete, a
            ještě vám přebývalo pro každé dobré dílo.
        </Lehrtext>
        <Lehrtextvers>2.Korintským 9,8</Lehrtextvers>
    </Losungen>
    <Losungen>
        <Datum>2016-01-18</Datum>
        <Sonntag/>
        <Wtag>Pondělí</Wtag>
        <Losungstext>Hospodin způsobuje na moři cestu, a na prudkých vodách stezku.</Losungstext>
        <Losungsvers>Izaiáš 43,16 K</Losungsvers>
        <Lehrtext>Neboj se, jen věř!</Lehrtext>
        <Lehrtextvers>Marek 5,36</Lehrtextvers>
    </Losungen>
    <Losungen>
        <Datum>2016-01-19</Datum>
        <Sonntag/>
        <Wtag>Úterý</Wtag>
        <Losungstext>Nebudete pokoušeti Hospodina Boha svého.</Losungstext>
        <Losungsvers>5.Mojžíšova 6,16 K</Losungsvers>
        <Lehrtext>Milujete-li mne, budete zachovávat má přikázání.</Lehrtext>
        <Lehrtextvers>Jan 14,15</Lehrtextvers>
    </Losungen>
    <Losungen>
        <Datum>2016-01-20</Datum>
        <Sonntag/>
        <Wtag>Středa</Wtag>
        <Losungstext>My také sloužiti budeme Hospodinu, neboť on jest Bůh náš.</Losungstext>
        <Losungsvers>Jozue 24,18 K</Losungsvers>
        <Lehrtext>Ať nás všichni pokládají za služebníky Kristovy a správce Božích tajemství.</Lehrtext>
        <Lehrtextvers>1.Korintským 4,1</Lehrtextvers>
    </Losungen>
    <Losungen>
        <Datum>2016-01-21</Datum>
        <Sonntag/>
        <Wtag>Čtvrtek</Wtag>
        <Losungstext>My, tvůj lid a stádo tvé pastvy, budeme na věky tebe vyznávat, tvou chválu od pokolení k pokolení
            vypravovat.
        </Losungstext>
        <Losungsvers>Žalm 79,13 Z</Losungsvers>
        <Lehrtext>Budete děkovat Otci, který vás připravil k účasti na dědictví svatých ve světle.</Lehrtext>
        <Lehrtextvers>Koloským 1,12</Lehrtextvers>
    </Losungen>
    <Losungen>
